export const orderStoreSchema = [
  { name: 'id', keypath: 'id', options: { unique: false } },
  { name: 'shop_id', keypath: 'shop_id', options: { unique: false } },
  { name: 'total_amount', keypath: 'total_amount', options: { unique: false } },
  { name: 'payment_method', keypath: 'payment_method', options: { unique: false } },
  { name: 'customer_id', keypath: 'customer_id', options: { unique: false } },
  { name: 'frontend_order_id', keypath: 'frontend_order_id', options: { unique: false } },
  { name: 'order_items', keypath: 'order_items', options: { unique: false } },
  { name: 'order_note', keypath: 'order_note', options: { unique: false } },
  { name: 'cash_tendered', keypath: 'cash_tendered', options: { unique: false } },
  { name: 'cash_balance', keypath: 'cash_balance', options: { unique: false } },
  { name: 'payment_network', keypath: 'payment_network', options: { unique: false } },
  { name: 'payment_status', keypath: 'payment_status', options: { unique: false } },
  { name: 'discount', keypath: 'discount', options: { unique: false } },
  { name: 'frontend_order_datetime', keypath: 'frontend_order_datetime', options: { unique: false } },
  { name: 'vat_value', keypath: 'vat_value', options: { unique: false } },
  { name: 'credit_amount_paid', keypath: 'credit_amount_paid', options: { unique: false } },
  { name: 'bank_id', keypath: 'bank_id', options: { unique: false } },
  { name: 'cheque_image', keypath: 'cheque_image', options: { unique: false } },
  { name: 'next_payment_date', keypath: 'next_payment_date', options: { unique: false } },
  { name: 'cheque_number', keypath: 'cheque_number', options: { unique: false } },
  { name: 'date_created', keypath: 'date_created', options: { unique: false } },
  { name: 'frontend_date_created', keypath: 'frontend_date_created', options: { unique: false } }
];
