export const productStoreSchema = [
  { name: 'id', keypath: 'id', options: { unique: false } },
  { name: 'shop_id', keypath: 'shop_id', options: { unique: false } },
  { name: 'product_name', keypath: 'product_name', options: { unique: false } },
  { name: 'product_group_id', keypath: 'product_group_id', options: { unique: false } },
  { name: 'selling_price', keypath: 'selling_price', options: { unique: false } },
  { name: 'supplier_id', keypath: 'supplier_id', options: { unique: false } },
  { name: 'supplier_price', keypath: 'supplier_price', options: { unique: false } },
  { name: 'new_low_stock_threshold', keypath: 'new_low_stock_threshold', options: { unique: false } },
  { name: 'image_url', keypath: 'image_url', options: { unique: false } },
  { name: 'description', keypath: 'description', options: { unique: false } },
  { name: 'is_service', keypath: 'is_service', options: { unique: false } },
  { name: 'product_does_not_expire', keypath: 'product_does_not_expire', options: { unique: false } },
  { name: 'new_quantity', keypath: 'new_quantity', options: { unique: false } },
  { name: 'expiry_date', keypath: 'expiry_date', options: { unique: false } },
  { name: 'barcode', keypath: 'barcode', options: { unique: false } },
  { name: 'serial_number', keypath: 'serial_number', options: { unique: false } },
  { name: 'vat_value', keypath: 'vat_value', options: { unique: false } },
  { name: 'vat_inclusive', keypath: 'vat_inclusive', options: { unique: false } },
  { name: 'apply_vat', keypath: 'apply_vat', options: { unique: false } },
  { name: 'tags', keypath: 'tags', options: { unique: false } },
  { name: 'product_id', keypath: 'product_id', options: { unique: false } },
  { name: 'color_code', keypath: 'color_code', options: { unique: false } },
  { name: 'is_available_oneline', keypath: 'is_available_oneline', options: { unique: false } },
  { name: 'price_list', keypath: 'price_list', options: { unique: false } },
  { name: 'date_created', keypath: 'date_created', options: { unique: false } },
  { name: 'frontend_date_created', keypath: 'frontend_date_created', options: { unique: false } }
];
